### ISSUE TITLE
Launch detail view in new tab

### ISSUE THREAD

**Issue by za158** [georgetown-cset/parat#104]
When clicking on a company name in the main table

**Comment by brianlove** [comment]
I'm hesitant about this for a couple reasons:

1. Since we are remaining on the same website (unlike with truly external links or the platform website), the user expectation would be that links work as normal.  In general, forcing links to open in a new tab should be avoided since it takes control out of the hands of the user.  If they want a link to open in a new tab there are multiple options available to them (Ctrl+click, middle click, or right click and open in a new tab, etc), whereas if they want to use the existing tab the only option is clicking (which by forcing a link to open in a new tab we are taking that option away from them).
2. When we're using normal/internal links the contents of the linked page can be prefetched, making detail pages load very quickly.  This is lost when we open in new tabs, as the linked contents isn't able to be prefetched.

Here's an article discussing when to (and when not to) open links in new tabs: https://css-tricks.com/use-target_blank/

One thing we could do though to enable both behaviors would be the main (company name) links remain as-is, but then add a separate [link icon](https://mui.com/material-ui/material-icons/?query=link&selected=OpenInNew) to open in a new tab.

**Comment by jmelot** [comment]
Brian's reasoning makes sense to me, but I think I'm with Zach because I find myself forcing the detail pages to open in new tabs every time I click on them. If the user has filtered PARAT to a set of companies that are of interest to them, it may not be obvious to them that hitting the back button will return them to their filtered view, and using the breadcrumbs would cause them to lose their filters. This would also match what we do in MoS.

**Comment by za158** [comment]
I agree with Jennifer agreeing with me.

**Comment by jmelot** [comment]
Well _I_ am agreeable to Zach agreeing with me agreeing with Zach, and hope that Brian agrees to agree with Jennifer agreeing with Zach agreeing with Jennifer agreeing with Za-

```
RecursionError: maximum recursion depth exceeded
```

**Comment by brianlove** [comment]
Closed by #152
