### ISSUE TITLE
Add highly cited article counts to data

### ISSUE THREAD

**Issue by jmelot** [georgetown-cset/parat#135]
Check with @za158 on intent

**Comment by jmelot** [comment]
Whatever we did in research almanac

**Comment by jmelot** [comment]
@rggelles let's talk about this tomorrow but this is one of the data issues I had in mind to ask of you, if you have time to help out. I think all that is needed is to add a count of the number of papers authored by each company that were within the top 10% of papers in AI by citations (@za158 correct me if I'm wrong and you wanted e.g. yearly counts as well)

**Comment by za158** [comment]
> (@za158 correct me if I'm wrong and you wanted e.g. yearly counts as well)

No

**Comment by rggelles** [comment]
Okay, I have follow-up questions here before I try to do this:

The first: what do you mean by "in the top 10% of papers in AI by citations?" I can think of a few possibilities here:

1. In the top 10% most cited papers among every paper selected by the AI classifier over all time (that is, since 2010, which is when the AI classifier started).
2. In the 10% most cited papers among every paper selected by the AI classifier in the given year they were published.

My inclination is that the latter of these makes more sense, since comparing papers to papers much older than them by citation percentiles doesn't make much sense to me (a paper from 2021 is going to almost definitely have fewer citations than a paper from 2016 just because it has had fewer years for people to cite it). But I'm not sure if that's what you're proposing so I want to be sure.

The second: you note that you don't want yearly counts here, but in that case we'd need to determine a year to cut off our counts at, right? What year would you want that to be? Right now our overall count cuts off at 2010, but my assumption has always been that since we have yearly counts for every other measure we're able to dynamically decide when we want to cut our yearly counts off at. Since we may want to have, say, a rolling yearly window, this seems preferable -- would it make sense to provide yearly counts on the back-end to facilitate this even if we don't show them on the front-end?

**Comment by jmelot** [comment]
Thanks for asking, top 10% within year (2) is good. And that's a good point about the yearly cutoff. It's fine if you want to just provide yearly counts starting from 2010, and we'll keep the logic for where to cut off for display in the data preprocessing code.

**Comment by rggelles** [comment]
I'm in the process of implementing this, but I would note for display purposes that I would highly recommend not displaying any data from 2023 or 2024 (and I'd remain hesitant at best about 2022).

The "highly cited" count (top 10% of papers) in 2024 is 3 citations. In 2023 it's 7. In 2022 it's 17. In most other years it's well above 60. That is -- papers just haven't had time to accumulate citations yet, so it's very hard to judge what a highly cited paper is in more recent years.

**Comment by rggelles** [comment]
This has been merged; closing.
