### ISSUE TITLE
Add patents granted metric

### ISSUE THREAD

**Issue by brianlove** [georgetown-cset/parat#146]
Add data regarding the number of applications that a company has filed for AI patents.

![parat-patent-applications-statbox](https://github.com/georgetown-cset/parat/assets/22353962/d16bc3a2-30f7-4558-9af8-3b35249218ae)

**Comment by jmelot** [comment]
Also, I'm looking through `get_ai_counts.py` and `linked_ai_patents.sql` and it appears that we're already counting patent applications, not granted patents. Is that correct? Do you think there's an argument for switching over to granted patents?

**Comment by rggelles** [comment]
Yes, when we did this initially, we specifically chose to use patent applications (and grants) rather than just patent grants.

This is what we have historically/consistently been recommended to do, especially in the area of AI patents, due to the fact that AI is a very new field when it comes to patents and patents have a very long lag in being granted (or even published). Particularly for new companies and startups that's going to make a huge difference. If you want to add a grant-only field you're welcome to, though -- as long as we're representing both this seems reasonable to me. It just made sense that when we were only doing one number the number to use was both applications and grants.

**Comment by jmelot** [comment]
Gotcha, thanks, that makes sense. I talked with @za158 about this, and I think he is ok with keeping the default patent metrics over applications, and with changing this specific value to the number of granted patents. Would you be able to help add that in?

**Comment by rggelles** [comment]
This should be completed with #196. Closing.
