### ISSUE TITLE
Set companies with no LinkedIn page to have N/A jobs instead of 0

### ISSUE THREAD

**Issue by rggelles** [georgetown-cset/parat#234]
So it doesn't appear they have no jobs when we just don't know their count.

**Comment by za158** [comment]
We should probably figure out some other procedurally generated alert/tooltip/value etc for cases like State Grid, which probably has a minimal LinkedIn presence compared to their actual employment footprint:

<img width="1353" alt="image" src="https://github.com/georgetown-cset/parat/assets/58824955/c33627d4-c1c9-4d13-8c70-2223d54ecaa5">

Could be as easy as putting an alert tooltip on the jobs stats for every non-US company since they are less likely to be well represented on LinkedIn
