### ISSUE TITLE
Not clear when the aggregate row appears

### ISSUE THREAD

**Issue by niharikasingh** [georgetown-cset/parat#250]
I took similar series of actions on both Safari and Chrome on iPhone iOS 15, but only Chrome showed the "totals" row at the bottom. Not clear to me why this would be. (This might be a "Neha is confused" issue not a "website needs fixing" issue.) 

<img width="1070" alt="Screenshot 2024-03-19 at 2 32 14 PM" src="https://github.com/georgetown-cset/parat/assets/3387590/c1a40ec7-ed7a-4de3-89e1-321e32b7fc37">

**Comment by brianlove** [comment]
The summary row appears when the user has selected specific companies or groups from the 'Company' dropdown.  We don't want to give summaries for the full set of PARAT companies since it's fairly arbitrary, but the S&P 500, Fortune Global 500, and user-defined company groups are all well-defined.

My guess is that the one on the right included S&P 500 and/or Fortune Global 500 whereas the one on the left is still of the whole dataset.
