### ISSUE TITLE
Confusing dropdown on detail page

### ISSUE THREAD

**Issue by niharikasingh** [georgetown-cset/parat#261]
This dropdown shows checkboxes, implying to me that I can select more than one option, but it only seems to allow selecting a single option. 

<img width="345" alt="Screenshot 2024-03-19 at 2 36 40 PM" src="https://github.com/georgetown-cset/parat/assets/3387590/75669da4-eed1-4456-a0b0-055e7412bcb8">

**Comment by jmelot** [comment]
@za158 for better wording

**Comment by brianlove** [comment]
@za158 This is happening because the patenting dropdown uses our `<Autocomplete>` component, which allows the user to type to filter the options, but always displays the checkboxes.  Meanwhile, the dropdown in the Publications section of the page above it uses our `<Dropdown>` component, which only shows the checkboxes when in multi-select mode.

Which of the following resolutions would you prefer?

1. Use a `<Dropdown>` in the Patents section, removing the checkboxes and also the ability to type to filter options.
2. Use an `<Autocomplete>` in the Publications section, leading to checkboxes in both menus but consistency throughout.
3. Make a change to the UI Components library so that `<Autocomplete>` only shows the checkbox icons when it is operating in multi-select mode.
4. Something else

**Comment by za158** [comment]
1, please
