### ISSUE TITLE
make active group row persistent

### ISSUE THREAD

**Issue by za158** [georgetown-cset/parat#328]
![image](https://github.com/georgetown-cset/parat/assets/58824955/da6233fd-d1fb-49fa-8ba0-a9ee307372ab)

@brianlove is it possible to have the S&P500 row stick as the user pages through results

**Comment by brianlove** [comment]
@za158 This will be quite difficult to pull off.

Essentially, what we're doing with the pinned rows is that rows that are "pinned" are sorted before any other non-pinned rows, regardless of their other comparisons.  This keeps them at the top of the table and can be understood by the underlying table component that we're using (MUI, the level beneath the `<Table>` component in the UI Components library).  So, from that underlying table's perspective, it's just displaying the rows in some order that it doesn't really care about, based on the current page.

I don't see any way to be able to tweak that sorting so that the pinned rows are at the top of every page.

I _have_ had a few thoughts at times about perhaps one day it'd be worth it to implement all of our (UIC) `<Table>` features directly, without relying on the external (MUI) component.  However, that is a _**massive**_ project and such thoughts remain theoretical at this point.

**Comment by za158** [comment]
So be it
