### ISSUE TITLE
rework extended metadata table

### ISSUE THREAD

**Issue by za158** [georgetown-cset/parat#370]
@jmelot Now that we have a sense of what the public dataset will look like, is it worth retooling the metadata table in company detail view to follow it?

![image](https://github.com/georgetown-cset/parat/assets/58824955/2b67bef1-4b3a-4432-9a70-24e1df4d4531)

Some of these "fields" are not going to be fields in the underlying dataset, and the Fortune 500 thing is weird to include since we're not going to have that at launch

**Comment by jmelot** [comment]
Yeah good point. I read over the dataset docs again and compared to what we currently have in the table. The only change that occurred to me was to remove "continent" since it's really just there for filtering purposes/people will know this from the country. Do you have anything else in mind?

Also I was noticing yesterday that we have code to include the canonical company name as one of the aliases. I don't remember why we decided to do that, but anyway do you still think that makes sense? I'm not sure I do but don't feel strongly

**Comment by za158** [comment]
> Yeah good point. I read over the dataset docs again and compared to what we currently have in the table. The only change that occurred to me was to remove "continent" since it's really just there for filtering purposes/people will know this from the country. Do you have anything else in mind?

Let's rework the table so it looks like this:

`Name
Country
Website
Stage
Tickers
Groups`

Under the table, add the following text: _Additional metadata about this company, including aliases, parent-subsidary relations, and unique identifiers in PARAT's [source datasets](link_tktk), are available in the [Private-Sector AI Indicators dataset](link_tktk)_

For tickers, only use US and China exchanges (https://github.com/georgetown-cset/parat/issues/273#issuecomment-2130049525)

Groups should list any Group (from Airtable) of which the company is a member, among all groups marked for display in the interface (eg not the Fortune 500)

> Also I was noticing yesterday that we have code to include the canonical company name as one of the aliases. I don't remember why we decided to do that, but anyway do you still think that makes sense? I'm not sure I do but don't feel strongly

I have no opinion on this whatsoever

**Comment by jmelot** [comment]
Bleh nevermind I'll just remove it. Actually looking over some aliases, they don't really seem to add a lot for a user
