### ISSUE TITLE
Add tooltip next to every column header

### ISSUE THREAD

**Issue by za158** [georgetown-cset/parat#401]
I am a little confused about whether this is going to happen naturally as a result of #267 and #377 and am making this issue in case not. There should be a tooltip next to every column heading in the main view. These can use the same text as in #267.

![image](https://github.com/georgetown-cset/parat/assets/58824955/d80a49fc-9059-4849-abcf-9fea4afc5d71)

**Comment by brianlove** [comment]
All columns support tooltips as of https://github.com/georgetown-cset/parat/pull/319, but most aren't showing because the tooltip text in `src/static_data/tooltips.js` is currently blank (instead of something like "zach_tktk").  Once text (or a React Fragment - see other tooltips) is added as values for those keys, the tooltips will automatically appear.
