### ISSUE TITLE
OpenAI has zero tech or AI jobs

### ISSUE THREAD

**Issue by za158** [georgetown-cset/parat#406]
Why
![image](https://github.com/georgetown-cset/parat/assets/58824955/2e3eedfd-2c28-4a06-975d-d6ddb5094d51)

Same for Anthropic...
![image](https://github.com/georgetown-cset/parat/assets/58824955/f3c27550-67eb-47fb-9201-92031d770b43)

**Comment by rggelles** [comment]
So I'm pretty sure the reason here is a really dumb annotation/code issue: it looks like you added OpenAI (and Anthropic) after the original annotation. If you look in the original annotation, you'll see that all the LinkedIn links don't have slashes at the end of them. That's because Revelio links don't either, so they won't match otherwise. Ultimately, this could be fixed in the code by dropping any ending slashes, or in the annotation by making sure no ending slashes existed on LinkedIns, but in the previous version I opted to handle it in the annotation rather than the code, and that's hitting us here.

**Comment by za158** [comment]
Oy gevalt. Thanks

@jmelot ?

**Comment by za158** [comment]
This issue appears to persist but not sure if it's just waiting for a data update
![image](https://github.com/georgetown-cset/parat/assets/58824955/031a2136-6bce-4fbf-bd71-6361b32a5e4d)

**Comment by jmelot** [comment]
Can you try an incognito window? This is what I see

![Screenshot 2024-06-18 at 3 56 08 PM](https://github.com/georgetown-cset/parat/assets/1252409/72cf1554-eb0f-41ac-90b7-9fc43cf2e649)

**Comment by za158** [comment]
Worked
