### ISSUE TITLE
Button overflow on mobile 

### ISSUE THREAD

**Issue by jmelot** [georgetown-cset/parat#464]
Just noticed this while checking the site on my phone. 

[Screenshot_20240625-212706.png](https://github.com/georgetown-cset/parat/assets/1252409/2f7b072a-3f29-4c8f-80de-d8e70d4aa5a5)

**Comment by jmelot** [comment]
We do have nice mobile-friendly buttons if you resize the screen to mobile, but they don't display if the page is already at mobile dimensions on load.

**Comment by jmelot** [comment]
I bet this was introduced here https://github.com/georgetown-cset/parat/commit/1eaba9004e4fc0f04aeedd2e5b7eee547e9b9970 - a hacky way to fix would be to add a param to `useWindowSize`, you may come up with a better way

**Comment by brianlove** [comment]
@jmelot @za158 I can make it so that the left and right halves of the button bar wrap onto separate lines when the viewport is too narrow, but then we get weirdness like this at medium widths:

![image](https://github.com/georgetown-cset/parat/assets/22353962/00117efc-a4a5-4153-887d-d9c6dd378d2e)

Theoretically this could be solved with a bunch of complicated JS to calculate how much space there is based on the "Viewing X of Y ..." labels and then show/hide button labels appropriately, but that'd be complicated to develop and require some significant testing to make sure it's all working as expected

(For what it's worth, the current version works perfectly until you filter the list 😆 )

**Comment by jmelot** [comment]
I'm not too opposed to that for intermediate cases. But we have mobile-friendly buttons that appear when you resize the screen from wide to narrow (which I'd forgotten), updating the code to have those display when the user initially loads a narrow page would be great
