### ISSUE TITLE
Add more pullouts for key stats in detail view

### ISSUE THREAD

**Issue by za158** [georgetown-cset/parat#88]
In pubs and patents: 5 year total, avg citations per paper, growth over past 5 years, % of company's publications that are AI publications (see #87)

**Comment by brianlove** [comment]
My interpretation of this: add additional stat boxes (but with text explanations next to them, as mocked up in #89) with the following values:

Publications
* "_5 year total_":
  * Sum of `articles.all_publications.counts` indices 5 through 9, inclusive (since index 10 is a partial year)
* "_avg citations per paper_":
  * `articles.citation_counts.total / articles.all_publications.total` (already existing, but needs text explanation)
* "_growth over past 5 years_":
  * `articles.all_publications.counts[9] / articles.all_publications.counts[4]`
* "_% of company's publications that are AI publications_":
  * `articles.ai_publications.total / articles.all_publications.total`

Patents
* "_5 year total_":
  * Sum of `patents.*.counts` indices 5 through 9 (inclusive) for all objects within `patents`  (alternatively, an `all_patents` entry could be added to the data)
* "_avg citations per paper_":
  * Seems not relevant to patents?
* "_growth over past 5 years_":
  * Like for publications, but using the calculated "`all_patents`" values
* "_% of company's publications that are AI publications_":
  * assuming "publications"-->"patents", `patents.ai_patents.total / (SUM_OF_ALL_PATENTS_TOTALS)`

@za158 Do those calculations match with what you were envisioning?

@jmelot Based on how often its used, I think the data should add a `all_patents` entry to aggregate all the various patent categories data-side.  I've made #125 to track this.

**Comment by za158** [comment]
Will confirm in the course of making the mockup we discussed early next week
---
Zachary Arnold
Analytic Lead, Emerging Technology Observatory (web <http://eto.tech> |
LinkedIn <https://www.linkedin.com/company/emerging-technology-observatory>
| Twitter <https://twitter.com/emergingtechobs>)
Center for Security and Emerging Technology
***@***.***

**Comment by za158** [comment]
> @za158 Do those calculations match with what you were envisioning?

This reads OK to me (please subtract 1 from the growth figures), but I'm not deep in the data itself and may be missing nuances to what some of these columns mean. Are there/should there be plans for a thorough review of the code and interface (once complete) by someone who is more familiar with the data (I guess Rebecca)? @brianlove @jmelot

**Comment by za158** [comment]
NB: The 10/23 mockup proposes a couple additional pullouts:

publications: # of highly cited articles, # of top conference articles, in each case over last 5 years
patents: # of patent applications filed in past 5 years

**Comment by jmelot** [comment]
@brianlove 

> My interpretation of this: add additional stat boxes (but with text explanations next to them, as mocked up in #89) with the following values:
> 
> Publications
> 
>     * "_5 year total_":
>       
>       * Sum of `articles.all_publications.counts` indices 5 through 9, inclusive (since index 10 is a partial year)

Yes, but I'd calculate it as an offset from the end of the array, in case we decide to include more years in the future

> 
>     * "_avg citations per paper_":
>       
>       * `articles.citation_counts.total / articles.all_publications.total` (already existing, but needs text explanation)

Yes - while I was checking, I decided to update the totals so they're only over the displayed years, as I think that's less potentially confusing (see https://github.com/georgetown-cset/parat/pull/130)

>     * "_growth over past 5 years_":
>       
>       * `articles.all_publications.counts[9] / articles.all_publications.counts[4]`

We use a more convoluted metric in MoS but I think this is clear and fine. Repeating my comment from above, I suggest you offset it from the end of the array
 
>     * "_% of company's publications that are AI publications_":
>       
>       * `articles.ai_publications.total / articles.all_publications.total`

👍 

> Patents
> 
>     * "_5 year total_":
>       
>       * Sum of `patents.*.counts` indices 5 through 9 (inclusive) for all objects within `patents`  (alternatively, an `all_patents` entry could be added to the data)

If this is meant to be all patents, we'll have to add it to the data separately, the counts in `patents` are all on the AI subset of patents (e.g. see https://github.com/georgetown-cset/parat/blob/version2/company_linkage/sql/adding_ai_patents_by_year_to_visualization.sql)

>     * "_avg citations per paper_":
>       
>       * Seems not relevant to patents?

@za158 did you have something else in mind here?

>     * "_growth over past 5 years_":
>       
>       * Like for publications, but using the calculated "`all_patents`" values

👍 

>     * "_% of company's publications that are AI publications_":
>       
>       * assuming "publications"-->"patents", `patents.ai_patents.total / (SUM_OF_ALL_PATENTS_TOTALS)`

Yes, this will also require a data addition

> This reads OK to me (please subtract 1 from the growth figures), but I'm not deep in the data itself and may be missing nuances to what some of these columns mean. Are there/should there be plans for a thorough review of the code and interface (once complete) by someone who is more familiar with the data (I guess Rebecca)? @brianlove @jmelot

Brian's questions were relative to the data I prepped for him and I can answer, but I'll also walk Rebecca through how her metrics are being used when the time comes
